Repository BuildForSDG/Team-269-Backend, pull requests merged in 2020-05, with the labels that each got.

#12 chore: delete default D-badge
  README.md
Labels: Ready For Review

#14 Add Laravel Linting
  README.md
  codesize.xml
  phpcs.xml
Labels: enhancement

#16 style: added spaces in sections
  README.md
Labels: documentation

#19 chore: add and update meta data
  app.properties
Labels: enhancement
